### PR TITLE
match_section should not match partial show tech sections

### LINKED ISSUE #26: match_section should not match partial show tech sections
See discussion in https://github.com/NCATComp410/comp410_fall_2020/issues/15 - fix match_section to more precisely match show tech sections

### PR DESCRIPTION
**Pull request by claesmk**
https://github.com/NCATComp410/comp410_fall_2020/issues/26

### CODE REVIEW

**Comment by claesmk** [comment]
Attaching unit-test coverage details

```
---------- coverage: platform darwin, python 3.8.5-final-0 -----------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
asa_parser/__init__.py                2      0   100%
asa_parser/src/asa_parse.py          22      1    95%
asa_parser/src/shtech_parse.py       27      1    96%
asa_parser/tests/__init__.py          0      0   100%
asa_parser/tests/test_parser.py      17      0   100%
-----------------------------------------------------
TOTAL                                68      2    97%

```

**Comment by scotter567** [comment]
I'm a little confused. What are unit tests and how do we not miss them?

**Comment by claesmk** [comment]
> I'm a little confused. What are unit tests and how do we not miss them?

The unit-tests are located in the [tests](https://github.com/NCATComp410/comp410_fall_2020/tree/dev/asa_parser/tests) directory.  If you are using pyCharm you can right-click on that folder to run the unit-tests.  The command line instructions are also in the [README](https://github.com/NCATComp410/comp410_fall_2020/blob/dev/README.md) in the Testing section. 

The tests automatically get run when a pull request is submitted as well - you can see that below "Show all checks" link

**Comment by claesmk** [comment]
Hi @scotter567 what do you think of the proposed changes?  Please review when you get a chance.  Here is more [documentation](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews) on how to review a pull request if you have any questions.

**Review by scotter567 — APPROVED** [review]
2 has me spooked in spooktober

**Pull request merged**
